### ISSUE TITLE
Sitemap.xml should contains only URLs from requested domain

### ISSUE THREAD

**Issue by hadimansouri** [pluf/seo#2]
For example URL such as example.pluf.ir should not be contained in the sitemap.xml of example.com.
We now add URLs of subdomain of tenants on the our cloud in the sitemap.xml of main domain of tenant.

Also, urls of main page of SPAs should ends with a slash (/) and equivalent URLs without last / should not add to sitemap.xml (this urls results in error)

**Comment by mostafabarmshory** [comment]
In the current version, user is responsible to add sitemap links
